---
- name: List currently installed domains
  shell: yunohost domain list --output-as json
  register: yunohost_installed_domains_raw
  changed_when: False

- name: Format json of domains
  set_fact: yunohost_installed_domains="{{ yunohost_installed_domains_raw.stdout | from_json }}"

- name: Create domains
  shell: yunohost domain add {{ item }} --admin-password {{ '%s' | format(yunohost.password) | quote }}
  with_items: "{{ yunohost.extra_domains }}"
  when: item not in yunohost_installed_domains.domains

- name: Fix certificates installation
  get_url:
    url: https://raw.githubusercontent.com/diafygi/acme-tiny/master/acme_tiny.py
    dest: /usr/lib/moulinette/yunohost/vendor/acme_tiny/acme_tiny.py
    checksum: sha256:53fa7f0782324c2451efde0220e599789289ce9e14c778d1c32da27c3ddc9283

- name: Install certificates
  shell: yunohost domain cert-install
  changed_when: False
