---
- name: Install requirements
  apt:
    name:
      - git
      - dialog
    state: present

- name: Test if Yunohost is already installed
  stat: path=/etc/yunohost/installed
  register: yunohost_file_install

- name: Test if Yunohost is package is present
  command: dpkg -l yunohost -q &> /dev/null && true
  ignore_errors: yes
  register: yunohost_pkg_present
  failed_when: False

- name: Download install script
  get_url:
    url: "{{ ynh_install_script.url }}"
    dest: /tmp/install_yunohost.sh
    mode: 700
    checksum: "{{ ynh_install_script.checksum }}"
  when: 
    - yunohost_file_install.stat.exists == False
    - yunohost_pkg_present

- name: Launch script
  command: /tmp/install_yunohost.sh -a
  when: 
    - yunohost_file_install.stat.exists == False
    - yunohost_pkg_present

- name: Launch postinstall
  shell: yunohost tools postinstall \
      --domain {{ yunohost.domain }} \
      --password {{ '%s' | format(yunohost.password) | quote }} \
      {% if yunohost.ignore_dyndns == True %} --ignore-dyndns {% endif %}
  when: 
    - yunohost_file_install.stat.exists == False

- name: Create domains
  include: domains.yml
  when: yunohost.extra_domains

- name: Add users
  include: users.yml
  when: yunohost.users

- name: Install apps
  include: apps.yml
  when: yunohost.apps
