---
- name: List users
  shell: yunohost user list --output-as json
  register: yunohost_registered_users_raw
  changed_when: False

- name: Format json of users
  set_fact: yunohost_registered_users="{{ yunohost_registered_users_raw.stdout | from_json }}"

- name: Create missing users
  shell: |
    yunohost user create {{ item.name }} --admin-password {{ '%s' | format(yunohost.password) | quote }} \
    -f {{ item.firstname }} \
    -l {{ item.lastname }} \
    -m {{ item.mail }} \
    -p {{ '%s' | format(item.pass) | quote }}
  with_items: "{{ yunohost.users }}"
  when: item.name not in yunohost_registered_users.users.keys()
